### ISSUE TITLE
Unable to add Service Content

### ISSUE THREAD

**Issue by dookgit** [iDigitalFlame/scorebot-core#8]
Released i posted this under my none usual git account, so...adding again :)  Apologises

OK, so i've got Scorebot running pretty well now.  And can monitor services etc.

I'm now trying to add a Service Content, which i assume is a way to check a service for specific content (e.g A specific webpage)

In the Django interface, whenever i try adding a Service Content, no matter what i set as the "Content Type" it fails, and gives me a big error. (Parts of it below)

![image](https://user-images.githubusercontent.com/10006917/68248635-f1b52200-0068-11ea-8e52-77534f29292f.png)

It seems to be related to scorebot_grid/models.py

![image](https://user-images.githubusercontent.com/10006917/68248615-e2ce6f80-0068-11ea-8910-10599df71a94.png)

Any ideas what could be causing this?
Many Thanks

**Comment by iDigitalFlame** [comment]
Thanks for the info!

I found the exact cause for this problem. Due to how Content objects where implemented, their One-to-One relationship was ment to be created during game init, but when creating via the Admin panel it fails due to lacking the Service object. The "__str__" function is causing this.

I am currently working on some bugfixes for scorebot, so I will roll this as well into the fix and close once pushed.

In the meantime, if you would like to create service content objects without issues. You can delete the "__str__" function from the Content model at scorebot_grid/models.py, line 445-447.

Thanks, I appreciate the input and feedback!

**Comment by dookgit** [comment]
![image](https://user-images.githubusercontent.com/10006917/68250307-63db3600-006c-11ea-88a6-f9a7af250d9b.png)

BOOM!   You absolute legend!   Thanks heaps for that man :)

**Comment by iDigitalFlame** [comment]
Fix was rolled into the v3.5 release.
